set(LEO_SOURCES
        src/engine.c
        src/error.c
        src/graphics.c
        src/keyboard.c
        src/image.c
        src/audio.c
        src/font.c
        src/collisions.c
        src/mouse.c
        src/gamepad.c
        src/pack_compress.c
        src/pack_errors.c
        src/pack_obfuscate.c
        src/pack_util.c
        external/miniaudio/miniaudio.c
        external/getopt/getopt.c
)

set(LEO_TEST_SOURCES
        tests/engine_test.cpp
        tests/error_test.cpp
        tests/graphics_test.cpp
        tests/keyboard_test.cpp
        tests/image_test.cpp
        #tests/caller_testing.cpp
        tests/audio_test.cpp
        tests/font_test.cpp
        tests/font_step2_load_draw_test.cpp
        tests/font_step3_spacing_rotation_test.cpp
        tests/collisions_test.cpp
        tests/mouse_test.cpp
        tests/gamepad_test.cpp
)
