set(LEO_SOURCES
        src/animation.c
        src/engine.c
        src/error.c
        src/graphics.c
        src/keyboard.c
        src/image.c
        src/audio.c
        src/font.c
        src/collisions.c
        src/mouse.c
        src/gamepad.c
        src/pack_compress.c
        src/pack_errors.c
        src/pack_obfuscate.c
        src/pack_util.c
        src/pack_reader.c
        src/pack_writer.c
        src/io.c
        src/macos_path_helper.c
        src/json.c
        src/base64.c
        src/pack_zlib.c
        src/csv.c
        src/gzip_pack.c
        src/signal.c
        src/tiled.c
        src/actor.c
        src/game.c
        src/touch.c
        src/transitions.c
        external/miniaudio/miniaudio.c
        external/getopt/getopt.c
        external/cJSON/cJSON.c
)

set(LEO_TEST_SOURCES
        tests/animation_test.cpp
        tests/engine_test.cpp
        tests/error_test.cpp
        tests/graphics_test.cpp
        tests/keyboard_test.cpp
        tests/image_test.cpp
        #tests/caller_testing.cpp
        tests/audio_test.cpp
        tests/font_test.cpp
        tests/font_step2_load_draw_test.cpp
        tests/font_step3_spacing_rotation_test.cpp
        tests/font_step5_vfs_tests.cpp
        tests/font_dynamic_rendering_test.cpp
        tests/collisions_test.cpp
        tests/mouse_test.cpp
        tests/gamepad_test.cpp
        tests/pack_rw_test.cpp
        tests/pack_writer_norm_test.cpp
        tests/pack_reader_edges_test.cpp
        tests/pack_zero_and_nospace_test.cpp
        tests/pack_obfuscation_edges_test.cpp
        tests/pack_tamper_test.cpp
        tests/python_compat_test.cpp
        tests/io_vfs_test.cpp
        tests/json_test.cpp
        tests/base64_test.cpp
        tests/csv_test.cpp
        tests/gzip_pack_test.cpp
        tests/macos_path_helper_test.cpp
        tests/macos_path_integration_test.cpp
        tests/signal_test.cpp
        tests/tiled_test.cpp
        tests/actor_test.cpp
        tests/game_test.cpp
        tests/touch_test.cpp
        tests/window_mode_test.cpp
        tests/transitions_test.cpp
        tests/windows_vfs_test.cpp
        tests/font_cache_test.cpp
)
