name: Build & Test Leo Engine Runtime

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

# Optional: cancel older runs on the same branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CTEST_OUTPUT_ON_FAILURE: "1"

jobs:
  macos:
    name: macOS (arm64, clang)
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: >
          cmake -S . -B build-${{ matrix.build_type }}-${{ matrix.shared }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DLEO_BUILD_SHARED=${{ matrix.shared }}
          -DLEO_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build-${{ matrix.build_type }}-${{ matrix.shared }} --parallel

      - name: Test
        run: ctest --test-dir build-${{ matrix.build_type }}-${{ matrix.shared }}

  windows-msvc:
    name: Windows (x64, MSVC)
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        shared: [ON, OFF]
    steps:
      - uses: actions/checkout@v4

      # Multi-config generator: pass -C at build/test time
      - name: Configure
        shell: pwsh
        run: >
          cmake -S . -B build-${{ matrix.build_type }}-${{ matrix.shared }}
          -G "Visual Studio 17 2022" -A x64
          -DLEO_BUILD_SHARED=${{ matrix.shared }}
          -DLEO_BUILD_TESTS=ON

      - name: Build
        shell: pwsh
        run: cmake --build build-${{ matrix.build_type }}-${{ matrix.shared }} --config ${{ matrix.build_type }} --parallel

      - name: Test
        shell: pwsh
        run: ctest --test-dir build-${{ matrix.build_type }}-${{ matrix.shared }} -C ${{ matrix.build_type }}

  debian12-gcc:
    name: Debian 12 (x64, gcc)
    runs-on: ubuntu-latest
    container:
      image: debian:12
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]
        shared: [ON, OFF]
    steps:
      - name: Install toolchain
        run: |
          set -eux
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config git ca-certificates libsdl2-dev xvfb xauth
          update-ca-certificates

      - uses: actions/checkout@v4

      - name: Configure
        env:
          CC: gcc
          CXX: g++
        run: >
          cmake -S . -B build-${{ matrix.build_type }}-${{ matrix.shared }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DLEO_BUILD_SHARED=${{ matrix.shared }}
          -DLEO_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build-${{ matrix.build_type }}-${{ matrix.shared }} --parallel

      - name: Test (headless via Xvfb)
        run: |
          xvfb-run -a -s "-screen 0 1280x720x24" \
            ctest --test-dir build-${{ matrix.build_type }}-${{ matrix.shared }} --output-on-failure

