name: Build & Test Leo Engine Runtime

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  macos-arm64:
    name: macOS (arm64, clang)
    runs-on: macos-14 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: macOS arm64 clang debug static
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          ./build/test_leo_runtime


      - name: macOS arm64 clang debug shared
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          ./build/test_leo_runtime


      - name: macOS arm64 clang release static
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          ./build/test_leo_runtime

      - name: macOS arm64 clang release shared
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          ./build/test_leo_runtime

  windows-x64:
    name: Windows (x64, MSVC cl.exe)
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Debug (Static)
        shell: pwsh
        working-directory: runtime
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          .\build\Debug\test_leo_runtime.exe

      - name: Build Debug (Shared)
        shell: pwsh
        working-directory: runtime
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          .\build\Debug\test_leo_runtime.exe

      - name: Build Release (Static)
        shell: pwsh
        working-directory: runtime
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          .\build\Release\test_leo_runtime.exe

      - name: Build Release (Shared)
        shell: pwsh
        working-directory: runtime
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          .\build\Release\test_leo_runtime.exe
          mkdir test_install
          cmake --install build --config Release --prefix test_install
          tree /F test_install


  debian12-gcc:
    name: Debian 12 (x64, gcc)
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Install build tools
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config git ca-certificates
          update-ca-certificates

      - name: Checkout
        uses: actions/checkout@v4

      - name: Debian Linux amd64 Debug (Static)
        env:
          CC: gcc
          CXX: g++
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          ./build/test_leo_runtime

      - name: Debian Linux amd64 Debug (Shared)
        env:
          CC: gcc
          CXX: g++
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Debug --parallel
          ./build/test_leo_runtime

      - name: Debian Linux amd64 Release (Static)
        env:
          CC: gcc
          CXX: g++
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=OFF -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          ./build/test_leo_runtime

      - name: Debian Linux amd64 Release (Shared)
        env:
          CC: gcc
          CXX: g++
        working-directory: runtime
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLEO_BUILD_SHARED=ON -DLEO_BUILD_TEST=ON
          cmake --build build --config Release --parallel
          ./build/test_leo_runtime
