name: Build Leo Engine Runtime

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  BUILD_DIR: build
  CMAKE_BUILD_TYPE: Debug
  LIB_OPTION: LEO_BUILD_SHARED=ON
  TEST_OPTION: LEO_BUILD_TESTS=ON

jobs:
  macos-arm64:
    name: macOS (arm64, clang)
    runs-on: macos-14 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you need Homebrew deps, uncomment and edit:
      # - name: Install deps (brew)
      #   run: |
      #     brew update
      #     brew install ninja pkg-config <your-deps>

      - name: Configure (CMake)
        run: |
          cmake -S . -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" \
            -D${LIB_OPTION} \
            -D${TEST_OPTION}

      - name: Build
        run: |
          cmake --build build --config "$CMAKE_BUILD_TYPE" --parallel
          # If you need specific targets:
          # cmake --build "$BUILD_DIR" --target your_target --parallel

  windows-x64:
    name: Windows (x64, MSVC cl.exe)
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure (CMake)
        shell: pwsh
        working-directory: runtime
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE="$env:CMAKE_BUILD_TYPE" -D"$env:LIB_OPTION" -D"$env:TEST_OPTION"

      - name: Build
        shell: pwsh
        working-directory: runtime
        run: |
          cmake --build build --config "$env:CMAKE_BUILD_TYPE" --parallel
          # Or target-specific builds:
          # cmake --build "$env:BUILD_DIR" --target your_target --parallel

      - name: Test
        shell: pwsh
        working-directory: runtime
        run: |
          .\build\test_leo_runtime.exe

  debian12-gcc:
    name: Debian 12 (x64, gcc)
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - name: Install build tools
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            build-essential cmake ninja-build pkg-config git ca-certificates
          update-ca-certificates

      - name: Checkout
        uses: actions/checkout@v4

      # Install project deps here (apt-get) if needed:
      # - name: Install project deps
      #   run: |
      #     apt-get install -y libsdl3-dev <your-deps>

      - name: Configure (CMake)
        env:
          CC: gcc
          CXX: g++
        run: |
          cmake -S . -B "$BUILD_DIR" \
            -G Ninja \
            -DCMAKE_BUILD_TYPE="$CMAKE_BUILD_TYPE" \
            -D${LIB_OPTION} \
            -D${TEST_OPTION}

      - name: Build
        run: |
          cmake --build "$BUILD_DIR" --config "$CMAKE_BUILD_TYPE" --parallel
          # Specific target example:
          # cmake --build "$BUILD_DIR" --target your_target --parallel

# Optional: upload built artifacts (uncomment & tweak)
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ runner.os }}-${{ github.sha }}
#          path: |
#            ${{ env.BUILD_DIR }}/your_binary_or_package
#            # add more paths as needed