name: Web (Emscripten)

on:
  workflow_dispatch:
  push:
    paths:
      - "src/**"
      - "include/**"
      - "CMakeLists.txt"
      - "cmake/**"
      - "tests/**"
      - ".github/workflows/emscripten.yml"

jobs:
  emscripten-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential cmake git python3 python3-pip curl pkg-config zip

      - name: Setup Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      - name: Configure (emcmake + CMake) with tests
        run: |
          source ./emsdk/emsdk_env.sh
          emcmake cmake -S . -B build-wasm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLEO_BUILD_SHARED=OFF \
            -DLEO_BUILD_TESTS=ON \
            -DCMAKE_C_EXTENSIONS=ON \
            -DCMAKE_CXX_EXTENSIONS=ON \
            -DCMAKE_C_FLAGS="-std=gnu11" \
            -DCMAKE_CXX_FLAGS="-std=gnu++17"

      - name: Build
        run: |
          source ./emsdk/emsdk_env.sh
          cmake --build build-wasm -j

      - name: List outputs
        run: |
          ls -lsah build-wasm || true
          find build-wasm -maxdepth 2 -type f -name "test_leo_runtime.*" -print

      - name: Run Catch2 under Node (skip window/graphics)
        run: |
          source ./emsdk/emsdk_env.sh
          # Catch2 test specs are passed as plain args; skip engine/window/graphics suites for Node
          node build-wasm/test_leo_runtime.js "~[engine] ~[graphics] ~[draw] ~[loop]"

